parameters:
    fastly_service_id: '%env(FASTLY_SERVICE_ID)%'
    fastly_key: '%env(FASTLY_KEY)%'

ezplatform:
    system:
        default:
            http_cache:
                # If using fastly, 'purge_server' must be set to 'https://api.fastly.com'
                fastly:
                    service_id: '%fastly_service_id%'
                    key: '%fastly_key%'
