# Base configuration for Elasticsearch
parameters:
    elasticsearch_dsn: "%env(ELASTICSEARCH_DSN)%"

ezplatform_elastic_search_engine:
    connections:
        default:
            hosts:
                - "%elasticsearch_dsn%"
