ezplatform.ee.calendar:
    resource: '@EzPlatformCalendarBundle/Resources/config/routing.yaml'
    defaults:
        siteaccess_group_whitelist: '%admin_group_name%'

ezplatform.ee.calendar.rest:
    resource: '@EzPlatformCalendarBundle/Resources/config/routing_rest.yaml'
    prefix: '%ezpublish_rest.path_prefix%'
