imports:
    - { resource: default_parameters.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: env/docker.php }
    - { resource: env/platformsh.php }

# Configuration for Database connection, can have several connections used by eZ Repositories in ezplatform.yml
doctrine:
    dbal:
        connections:
            default:
                driver: "%database_driver%"
                host: "%database_host%"
                port: "%database_port%"
                user: "%database_user%"
                password: "%database_password%"
                dbname: "%database_name%"
                charset: UTF8

# Base configuration for Solr, for more options see: https://doc.ez.no/display/EZP/Solr+Search+Engine+Bundle
# Can have several connections used by each eZ Repositories in ezplatform.yml
ez_search_engine_solr:
    endpoints:
        endpoint0:
            dsn: "%solr_dsn%"
            core: collection1
    connections:
        default:
            entry_endpoints:
                - endpoint0
            mapping:
                default: endpoint0

# Stash is used for persistence cache in eZ Repository
# Can have several caches used by different eZ Repositories in ezplatform.yml, must be one per database
stash:
    caches:
        default:
            drivers:
                # When using multiple webservers, you must use Memcache or Redis to share the cache
                # For single web server Apc, Memcached and Redis will give you better performance under editing load
                - FileSystem
            inMemory: true
            registerDoctrineAdapter: false
            # On Windows, using FileSystem, to avoid hitting filesystem limitations
            # you need to change the keyHashFunction used to generate cache directories to "crc32"
            # FileSystem:
            #    keyHashFunction: crc32
    # Disable tracking of cache values to avoid large disk use when using web profiler
    tracking_values: false

framework:
    esi:             ~
    translator:      { fallback: "%locale_fallback%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    csrf_protection: ~
    form:
        csrf_protection:
            enabled: true
            # Note: changing this will break legacy extensions that rely on the default name to alter AJAX requests
            # See https://jira.ez.no/browse/EZP-20783
            field_name: ezxform_token
    validation:      { enable_annotations: true }
    # Place "eztpl" engine first intentionnally.
    # This is to avoid template name parsing with Twig engine, refusing specific characters
    # which are valid with legacy tpl files.
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale_fallback%"
    trusted_hosts:   ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        # Note: eZ Publish also allows session name and session cookie configuration to be per SiteAccess, by
        #       default session name will be set to "eZSESSID{siteaccess_hash}" (unique session name per siteaccess)
        #       Further reading on sessions: https://doc.ez.no/display/EZP/Session
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ eZStudioDemoBundle, EzSystemsPersonalizedBlockBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        bootstrap_glyphicons_eot:
            inputs:
                - "%kernel.root_dir%/../vendor/components/bootstrap/fonts/glyphicons-halflings-regular.eot"
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - "%kernel.root_dir%/../vendor/components/bootstrap/fonts/glyphicons-halflings-regular.svg"
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_ttf:
            inputs:
                - "%kernel.root_dir%/../vendor/components/bootstrap/fonts/glyphicons-halflings-regular.ttf"
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_woff:
            inputs:
                - "%kernel.root_dir%/../vendor/components/bootstrap/fonts/glyphicons-halflings-regular.woff"
            output: "fonts/glyphicons-halflings-regular.woff"
        bootstrap_glyphicons_woff2:
            inputs:
                - "%kernel.root_dir%/../vendor/components/bootstrap/fonts/glyphicons-halflings-regular.woff2"
            output: "fonts/glyphicons-halflings-regular.woff2"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
