ezpublish:
    # Repositories configuration, setup default repository to support solr if enabled
    repositories:
        default:
            fields_groups:
                list: [content, seo, meta]
                default: content
            storage: ~
            search:
                engine: "%search_engine%"
                connection: default

    # Siteaccess configuration, with one siteaccess per default
    siteaccess:
        list:
          - site
          - fr
          - de
          - no
        groups:
            site_group:
                - site
                - fr
                - de
                - no
        default_siteaccess: site
        match:
            URIElement: 1

    # System settings, grouped by siteaccess and/or siteaccess group
    system:
        site_group:
            # Pool to use for cache, needs to be different per repository (database).
            cache_pool_name: '%cache_pool%'
            # These reflect the current installers, complete installation before you change them. For changing var_dir
            # it is recommended to install clean, then change setting before you start adding binary content, otherwise you'll
            # need to manually modify your database data to reflect this to avoid exceptions.
            var_dir: var/site
        site:
            languages:
                - eng-GB
                - fre-FR
                - ger-DE
                - nor-NO
        fr:
            languages:
                - fre-FR
                - eng-GB
        de:
            languages:
                - ger-DE
                - eng-GB
        no:
            languages:
                - nor-NO
                - eng-GB
