ezpublish:
     http_cache:
          purge_type: '%purge_type%'
     repositories:
          default:
               storage: null
               search:
                    engine: '%search_engine%'
                    connection: default
     siteaccess:
          list:
               - site
               - admin
               - test
          groups:
               site_group:
                    - site
                    - test
               admin_group:
                    - admin
          default_siteaccess: site
          match:
               Map\Host:
                    ezeedev.local: site
                    ezeedev-admin.local: admin
                    ezeedev-test.local: test
     system:
          default:
               cache_service_name: '%cache_pool%'
               var_dir: var/site
               content:
                    default_ttl: '%httpcache_default_ttl%'
               http_cache:
                    purge_servers:
                         - '%purge_server%'
                    varnish_invalidate_token: '%varnish_invalidate_token%'
                    fastly:
                         service_id: '%fastly_service_id%'
                         key: '%fastly_key%'
          admin_group:
               languages:
                    - eng-GB
                    - pol-PL
               page_builder:
                    siteaccess_list:
                         - site
                         - test
               content_tree_module:
                    contextual_tree_root_location_ids:
                         - 2
                         - 5
                         - 43
                         - 48
                         - 55
               subtree_paths:
                    content: /1/2/
                    media: /1/43/
          site:
               languages:
                    - eng-GB
          test:
               languages:
                    - pol-PL
                    - eng-GB
     url_alias:
          slug_converter:
               transformation: urlalias_lowercase
ez_platform_standard_design:
     override_kernel_templates: false
